project:
  type: website
  output-dir: docs
  
website: 
  title: "FMDV Co-Infection"
  navbar:
    left:
      - href: preprocessing.qmd
        text: Preprocessing 
      - href: entanglement.qmd
        text: Entanglement
      - href: time_tree.qmd
        text: Phylogeny 
    right:
      - href: https://geoepi.github.io/
        text: GeoEpi
      - icon: github
        href: https://github.com/geoepi/pak-coinfection
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: lux
    toc: true
    
editor: source

